#!/usr/bin/env python
import sys
sys.path.insert(0, 'src')

from Site import BuildConfig, SiteConfig
from ArticleLoader import ArticleLoader
from SiteLoader import SiteLoader
from SiteBuilder import SiteBuilder

if __name__ == '__main__':
  site_loader = SiteLoader()
  site_loader.Load()
  builder = SiteBuilder(site_loader.build_config, is_incremental=False)
  builder.BuildSite(site_loader.site_config)
