site_title: Sample Lightning Blog
date_format: '%d %B %Y'
permalink_formats:
  post: '{{slug}}'
  page: '{{slug}}'
  draft: 'drafts/{{slug}}'
  archive: '{{slug}}'
  feed: '{{slug}}'
  book: 'books/{{slug}}'
type_mapping:
  /pages/: 'page'
  /posts/: 'post'
default_type: 'page'
