site_title: metajungle
date_format: '%d %B %Y'
verbs:
  post: 'Published'
  talk: 'Presented'
  link: 'Linked'
permalink_format:
  post: '{{year}}/{{month}}/{{slug}}'
  page: '{{slug}}'
  draft: 'drafts/{{slug}}'
  archive: '{{slug}}'
  feed: '{{slug}}'
  index: ''
